[tox]
envlist = py,docs,doctest,ruff,ruff-format,pyright

[testenv]
deps =
    pytest
    pytest-cov
commands =
    py.test --basetemp={envtmpdir} --cov=cachetools --cov-report term-missing {posargs}

[testenv:docs]
deps =
     sphinx
commands =
     sphinx-build -W -b html -d {envtmpdir}/doctrees docs {envtmpdir}/html

[testenv:doctest]
deps =
     sphinx
commands =
     sphinx-build -W -b doctest -d {envtmpdir}/doctrees docs {envtmpdir}/doctest

[testenv:ruff]
deps =
    ruff
commands =
    ruff check {posargs}
skip_install = true

[testenv:ruff-format]
deps =
    ruff
commands =
    ruff format --diff -q {posargs}
skip_install = true

[testenv:pyright]
deps =
    pyright
commands =
    pyright {posargs}
skip_install = true
